# Generated by Django 3.1.4 on 2020-12-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_couponblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponblock',
            name='used',
            field=models.IntegerField(default=0, verbose_name='Usado?'),
        ),
    ]
