# Generated by Django 3.1.4 on 2020-12-22 18:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0012_auto_20201222_0014'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0004_auto_20201222_0952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CouponBlock',
            new_name='CuponBlock',
        ),
    ]
