# Generated by Django 3.1.4 on 2020-12-28 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20201222_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuponblock',
            name='used',
        ),
    ]
