# Generated by Django 3.1.4 on 2020-12-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_remove_cuponblock_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuponblock',
            name='used',
            field=models.IntegerField(default=0, verbose_name='Usado?'),
        ),
    ]
