# Generated by Django 3.1.5 on 2021-01-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_cuponblock_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Member', 'member'), ('Free', 'free'), ('admin', 'admin')], default='Member', max_length=30),
        ),
    ]
