# Generated by Django 3.1.4 on 2020-12-15 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30, verbose_name='url del sitio')),
                ('title', models.CharField(max_length=100, verbose_name='Nombre')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='logos')),
                ('horario', models.TextField(blank=True, default='soy un horario', verbose_name='horario')),
                ('location', models.TextField(blank=True, default='soy un Mapa :D', verbose_name='Ubicacion de Lugar')),
                ('phone_number', models.CharField(blank=True, max_length=12, verbose_name='numero de telefono')),
                ('city', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=30, verbose_name='Estado')),
                ('featured', models.BooleanField(default=True, verbose_name='Aparece en el landing>?')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30, verbose_name='slug para categorias')),
                ('title', models.CharField(max_length=30, verbose_name='Titulo')),
                ('description', models.TextField(max_length=300, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fs_category', models.CharField(max_length=30, verbose_name='Categoria food / service')),
                ('fs_orden', models.IntegerField(default=1, verbose_name='Orden food / service')),
                ('fs_name', models.CharField(max_length=30, verbose_name='Nombre food / service')),
                ('fs_description', models.TextField(blank=True, verbose_name='Descripcion food / service')),
                ('fs_image', models.ImageField(blank=True, null=True, upload_to='place', verbose_name='Imagen food / service')),
                ('fs_price', models.CharField(blank=True, max_length=6, verbose_name='Precio food / service')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place', verbose_name='restaurante')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='place_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.placetype', verbose_name='Tipo de servicio'),
        ),
    ]
