# Generated by Django 3.1.4 on 2020-12-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placetype',
            name='title',
            field=models.CharField(choices=[('Restaurant', 'restaurant'), ('Services', 'services'), ('Personal Care', 'personal care'), ('Markets', 'markets')], default='Restaurant', max_length=30, verbose_name='titulo'),
        ),
    ]
