# Generated by Django 3.1.4 on 2020-12-17 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_auto_20201216_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='#')),
                ('title', models.CharField(max_length=30, verbose_name='titulo cupon')),
                ('description', models.CharField(blank=True, max_length=80, verbose_name='descripcion cupon')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place', verbose_name='restaurante')),
            ],
        ),
    ]
