# Generated by Django 3.1.4 on 2020-12-21 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_descuentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentos',
            name='cupon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='place.cupon', verbose_name='Cupon'),
        ),
    ]
