# Generated by Django 3.1.4 on 2020-12-21 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_auto_20201220_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentos',
            name='cupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.cupon', verbose_name='Cupon'),
        ),
    ]
