# Generated by Django 3.1.4 on 2020-12-22 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_remove_descuentos_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descuentos',
            name='cupon',
        ),
        migrations.AddField(
            model_name='cupon',
            name='cupon_usado',
            field=models.IntegerField(default=0, verbose_name='se uso?'),
        ),
        migrations.AddField(
            model_name='cupon',
            name='cupon_used',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='place.descuentos'),
        ),
    ]
