# Generated by Django 3.1.4 on 2020-12-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_auto_20201221_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='number',
            field=models.IntegerField(verbose_name='#'),
        ),
    ]
