# Generated by Django 3.1.4 on 2020-12-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_auto_20201221_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupon',
            name='cupon_used',
        ),
        migrations.DeleteModel(
            name='Descuentos',
        ),
    ]
