# Generated by Django 3.1.4 on 2020-12-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0011_auto_20201221_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupon',
            old_name='cupon_usado',
            new_name='cupon_used',
        ),
        migrations.AlterField(
            model_name='cupon',
            name='number',
            field=models.IntegerField(default=0, verbose_name='#'),
        ),
    ]
