# Generated by Django 3.1.4 on 2021-01-08 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0012_auto_20201222_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_owner', models.CharField(max_length=30, verbose_name='nombre del responsable')),
                ('phone_owner', models.IntegerField(max_length=12, verbose_name='telefono del responsable')),
                ('email_owner', models.EmailField(max_length=30, verbose_name='email del responsable')),
                ('terms', models.BooleanField(default=True, verbose_name='Acepto terminos y condiciones')),
                ('place_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place', verbose_name='Nombre del negocio')),
            ],
        ),
    ]
