# Generated by Django 3.1.4 on 2021-01-11 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0014_auto_20210107_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='terms',
            field=models.BooleanField(default=False, verbose_name='Acepto terminos y condiciones'),
        ),
        migrations.CreateModel(
            name='PlaceMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.IntegerField(blank=True, max_length=9, verbose_name='Latitud')),
                ('longitud', models.IntegerField(blank=True, max_length=9, verbose_name='Longitud')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place', verbose_name='Lugar')),
            ],
        ),
    ]
