# Generated by Django 3.1.5 on 2021-01-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0015_auto_20210111_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placemap',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=15, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='placemap',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=15, verbose_name='Longitud'),
        ),
    ]
