# Generated by Django 3.1.5 on 2021-01-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0017_auto_20210117_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='sample',
            field=models.ImageField(blank=True, null=True, upload_to='samples', verbose_name='Imagen Muestra'),
        ),
    ]
